# Generated by Django 3.2 on 2021-09-27 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import register.apps.web.blog.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID CODE')),
                ('empl_code', models.CharField(default=register.apps.web.blog.utils.employee_randcode_gen, max_length=100, verbose_name='CODE')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('fullname', models.CharField(max_length=100, verbose_name='FULLNAME')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Invalid Phone Number', regex='^[ 0-9]+$')], verbose_name='PHONE NUMBER')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='SLUG')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.position', verbose_name='POSITION')),
            ],
            options={
                'verbose_name_plural': 'employees',
                'db_table': 'Employee',
            },
        ),
    ]
