# Generated by Django 3.0.8 on 2021-01-18 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bool_deleted',
            field=models.BooleanField(default=False, verbose_name='IS DELETED?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DATE CREATED'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empl_code',
            field=models.CharField(max_length=3, verbose_name='EMPLOYEE CODE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='FULLNAME'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='MOBILE'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=50, verbose_name='TITLE'),
        ),
    ]
