# Generated by Django 3.0.8 on 2021-01-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
