# Generated by Django 3.2 on 2021-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='SLUG'),
            preserve_default=False,
        ),
    ]
